name: Release

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "If not patch specifiy release tag"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish extension
    outputs:
      new-version: ${{ steps.patched-tag.outputs.new_version }}
      new-tag: ${{ steps.patched-tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Bump version
        id: patched-tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          custom_tag: ${{ github.event.inputs.custom_tag }}

      - name: Update package.json version
        run: jq '.version = "${{ steps.patched-tag.outputs.new_version }}"' package.json > tmp.package.json && mv tmp.package.json package.json

      - name: Build
        run: yarn vscode:prepublish

      - name: Setup VSCE
        run: yarn global add vsce@2.11.0

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    environment: Stable
    name: Release
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Setup VSCE
        run: yarn global add vsce@2.11.0

      - name: Package VSIX
        run: echo y | vsce package

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.publish.outputs.new-tag }}
          tag_name: ${{ needs.publish.outputs.new-tag }}
          body: '${{ steps.extract-release-notes.outputs.release_notes }}'
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            **/*.vsix